blank_issues_enabled: true
contact_links:
  - name: ğŸ¤– æé—®ã€æä¾›åé¦ˆã€åˆ†äº«ä½ çš„é¡¹ç›®
    url: https://github.com/mallfoundry/taroify/discussions
    about: é€šè¿‡ Discussions è®¨è®ºåŒºè”ç³»å…¶ä»–ç¤¾åŒºæˆå‘˜
  - name: ğŸ“± é€šè¿‡å¾®ä¿¡è·å–å¸®åŠ©
    url: https://github.com/mallfoundry/taroify#%E5%BE%AE%E4%BF%A1%E4%BA%A4%E6%B5%81%E7%BE%A4
    about: æ‰“å¼€é“¾æ¥æ‰«æäºŒç»´ç ï¼Œé€šè¿‡å¾®ä¿¡è®¨è®ºç»„è·å¾—å¸®åŠ©
